version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8200"
    volumes:
      - ./app/:/home/appuser/app
    environment:
      - MONGO_USER=root
      - MONGO_PASSWORD=example
    depends_on:
      - mongo
  web_test:
    build: .
    ports:
      - "8000:8200"
    volumes:
      - ./app/:/home/appuser/app
    command: ["pytest", "--cov-report", "term", "--cov=.", "tests/"]
    profiles:
      - tests
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example