version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8200"
    volumes:
      - ./app/:/home/appuser/app
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example